disabledMods = [
    "minecraft",
    "aeronauticswinds",
    "artifacts",
    "beachparty",
    "bits_n_bobs",
    "bloomingnature",
    "cardboarded_conveynience",
    "chipped",
    "computercraft",
    "copycats",
    "create",
    "create_connected",
    "create_dragons_plus",
    "create_enchantment_industry",
    "create_hypertube",
    "create_rns",
    "createadditionallogistics",
    "createbb",
    "createbigcannons",
    "createcasing",
    "createcobblestone",
    "createdeco",
    "createdieselgenerators",
    "createestrogen",
    "createframed",
    "creategoggles",
    "createpropulsion",
    "createrailwaysnavigator",
    "escalated",
    "estrogen",
    "extra_gauges",
    "fairylights",
    "farm_and_charm",
    "fluidlogistics",
    "gnkinetics",
    "herbalbrews",
    "hex_js",
    "hexcasting",
    "interiors",
    "lilis_pottery",
    "meadow",
    "numismatics",
    "powergrid",
    "rechiseled",
    "rechiseledcreate",
    "scguns",
    "simulated_addition",
    "sophisticatedbackpacks",
    "trading_floor",
    "vista"
]