#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Sun Aug 30 16:46:51 MSK 2026
=======
#Sun Aug 30 20:43:37 EEST 2026
>>>>>>> origin/master
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
